name: Publish stable

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      deployments: write
      contents: write
      statuses: write
      actions: write
      checks: read

    steps:
      - name: 'Checkout' # Download code from the repository
        uses: actions/checkout@v2 # Public action
        with:
          fetch-depth: 0 # Checkout all branches and tags

      - name: 'Use NodeJS 16' # Setup node using version 14
        uses: actions/setup-node@v2 # Public action
        with:
          node-version: '16.15.1'

      - name: 'Setup lerna@6.6.2'
        run: yarn global add lerna@6.6.2 --ignore-engines

      - name: Install and link dependencies
        run: |
          yarn --cwd ./packages/ui-shared install --force --ignore-engines
          yarn --cwd ./packages/ui-shared dev:prepare
          lerna bootstrap

      - name: 'Setup npm'
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Version and publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"

          lerna version prerelease --force-git-tag --no-changelog --yes
          lerna publish from-git --force-git-tag --dist-tag latest --yes --summary-file
